### ISSUE TITLE
attributes.id not rendering in Neos 1.2.5

### ISSUE THREAD

**Issue by ericstumper** [million12/Neos.Plugin.SlickCarousel#2]
Hi,

I just installed your Plugin on Neos 1.2.5 and recognized that the attributes.id is not rendered in the template. There seems to be a problem with assigning a variable to attributes.id.

```
attributes.id = ${slickElementId}
```

is not rendering the id.

If I use:

```
attributes.id = 'test'
```

it is working fine.

The following is working fine as well:

```
attributes.id = ${q(node).property('customHtmlId') ? q(node).property('customHtmlId') : 'slick-'+q(node).property('_identifier')}
```

So it seems you can't assign a variable to attributes.id or ${slickElementId} doesn't contain a string which I guess would throw an exception.

I also noticed that the property for customHtmlId is missing in NodeTypes.yaml

**Comment by ryzy** [comment]
Hi Eric,

Did you use v0.1.0 or current dev-master? That v0.1.0 was the one working with Neos 1.2.x, the current dev-master is tested with Neos 2.0 only.

But... I guess we could make it working on both versions - the thing is it's getting harder to test it in older versions, as all my projects are based now on Neos 2.0-dev by now... ;)

**Comment by ryzy** [comment]
No reply to it, closing.
